services:
  pg-shard-1:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '15433:5432'
  pg-shard-2:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '15434:5432'
