spring:
  application:
    name: postgres-sharding-demo
  flyway:
    enabled: false
postgres:
  shard1:
    datasource:
      url: jdbc:postgresql://localhost:15433/postgres
      username: postgres
      password: secret
  shard2:
    datasource:
      url: jdbc:postgresql://localhost:15434/postgres
      username: postgres
      password: secret
